name: Ini tugas 20 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.5.0

    - name: Setup gradlew
      run: chmod +x gradlew
      
    - name: Execute Test
      run: ./gradlew cucumberTest

          

   
